# Nome da aplicação
spring.application.name=literalura

# Credenciais do PostgreSQL (Preencha com seus dados reais)
spring.datasource.url=jdbc:postgresql://localhost:5432/literalura
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate (Mapeamento Objeto-Relacional)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true